### ISSUE TITLE
Update Reactos for well running Classic Shell ;)

### ISSUE THREAD

**Issue by blackcrack** [coddec/Classic-Shell#17]
<details><summary>Original Text</summary><p>
<code>
Hi,
i have see the postings and have also read to be Win10 awful , indeed right, 
so, why not helping Reactos for use Classic-shell too ;)
Can you check out the repo from Reactos maybe (here in Github)

best regards
Blacky
</code>
</p></details>
Hi,

I have seen the blog post and I have read articles about Windows 10 being awful.

Would it be possible to improve ReactOS' compatibility with Classic-Shell?

Best regards,
Blacky

EDIT by @Xenhat: Improved wording.

**Comment by Quentinix** [comment]
Windows 10 horrible you said?
As for all addictions to software, you have to go ahead and get in the habit, personally I prefer windows 8.1 with its subway interface ... but it's another discussion!

Classic shell must already adapt for windows 10, but if another person is able to recode with a fork or since zero, why not, but I do not think that Coddec wants to integrate this into the repository.
In addition, ReactOS does not yet have a good version for a classic shell on ReactOS.

**Comment by blackcrack** [comment]
Hi Quentinix,
not me, i think me this also only and hold Win10 in VBox behind prison bars ;) hihi ,
i use still Win7 with the regkey for not update to 10.. up to Reactos is usable
no, it was in the Forum : 
http://www.classicshell.net/forum/viewtopic.php?f=4&t=8147

by the way : https://github.com/reactos
if anyone want integrate the escape color code, for a good terminal emu,
can he do it in cmd.exe

**Comment by XenHat** [comment]
@blackcrack I have edited your question so that people reading this in the future will understand what you meant.

As for the question itself, This is the Classic Shell issue tracker, for topics concerning the Classic Shell code itself. I do not believe it is the best place to ask for help about ReactOS in here. Please create a new issue if you would rather ask for Classic Shell development to try to add support for ReactOS.

**Comment by blackcrack** [comment]
thank you for closing it and nobody see it any more .. oh mann.. *negativa thumps down* :-1: 
oh mann girlys .. what do you meant why  Quentinix this not closed ? (specially for you: closed is HIDDEN !)
oh man, i be now a bit pissed on.. pffhh.. thank you for the remove for Reactos adversiting ! and therewith removing for eventually help !!
bahh go in the corner Girly or out of the room !
